
version: '2.1'

volumes:
    ros-bin: 
    opencv-lib: 
    opencv-include: 
    usr-lib:

services:
  roscore:
    image: cristidragomir97/roscore
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=roscore
        - ROS_MASTER_URI=https://347aba3bd2d859f629697927fc4909e5.balena-devices.com:11311
    links: 
      - rosboard
      - camera
      - robot-block
    ports:
      - "11311:11311"
    volumes:
      - ros-bin:/opt/ros/noetic
      - opencv-lib:/usr/local/lib/opencv
      - opencv-include:/usr/local/include/opencv
      - usr-lib:/usr/lib/aarch64-linux-gnu


############################################################################################################
# robot-block is a hardware abstraction layer for I2C, UART and GPIO modules for the Raspberry Pi Eosystem
# Is creates all the required ROS handlers for your hardware based on a configuration file. 
# Long story short it's docker-compose for hardware
############################################################################################################
  robot-block:
    privileged: true
    build: .
    environment: 
       - UDEV=1
       - ROS_HOSTNAME=robot-block-lib
        - ROS_MASTER_URI=https://347aba3bd2d859f629697927fc4909e5.balena-devices.com:11311
    volumes:
      - ros-bin:/opt/ros/noetic
      - opencv-lib:/usr/local/lib/opencv
      - opencv-include:/usr/local/include/opencv
      - usr-lib:/usr/lib/aarch64-linux-gnu
    ports:
      - "8000:80"
      - "5000:5000"
    devices:
      - "/dev:/dev"